### ISSUE TITLE
problem with start.bat on MacOS

### ISSUE THREAD

**Issue by dengjon** [LaplaceFourior/download_somthing_from_web#1]
Hello! While I'm using your excellent tools in Mac terminal, some error occurred, which is shown as below:
> download_somthing_from_web-master ./start.bat
./start.bat: line 1: @echo: command not found
Creating virtual environment...
./start.bat: line 4: syntax error near unexpected token `('
./start.bat: line 4: `if not exist venv ('

Waiting for your help! tks.

**Comment by LaplaceFourior** [comment]
Appreciate for using it! I have already  add a script that will work on macos or linux for the start-up. Hope it will help.

**Comment by dengjon** [comment]
@LaplaceFourior I've tried the new version `start.sh` in Mac terminal. The error occurred before disappeared. But sadly some new problems occurs.
> download_somthing_from_web-master ./start.sh
Creating virtual environment...
Virtual environment created.
Activating virtual environment...
Virtual environment activated.
grep: illegal byte sequence
Installing required packages...
ERROR: Invalid requirement: '\udcff\udcfebeautifulsoup4==4.12.2'
Packages installed.
Starting application...
➜  download_somthing_from_web-master Traceback (most recent call last):
  File "/Users/dengjon/Downloads/download_somthing_from_web-master/main.py", line 1, in <module>
    from app import create_app
  File "/Users/dengjon/Downloads/download_somthing_from_web-master/app/__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

Maybe some problems with the requirements.txt and external packages. :)
